jobs:
  - job: frontend_build
    displayName: Frontend build
    pool:
      vmImage: ubuntu-latest
    steps:
      - checkout: self

      - task: NodeTool@0
        displayName: Use Node.js $(NODE_VERSION)
        inputs:
          versionSpec: $(NODE_VERSION)

      - script: |
          cd apps/dashboard
          npm install --legacy-peer-deps
          npm run build
        displayName: Build dashboard
