apiVersion: v1
kind: Service
metadata:
  name: {{ include "remediai.fullname" . }}-api
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.api.port }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "remediai.name" . }}
    app.kubernetes.io/component: api
