"""Unit tests for docs source-to-site sync helpers."""

from __future__ import annotations

import runpy
from pathlib import Path
from typing import Any

import pytest


def _load_sync_module() -> dict[str, Any]:
    module_path = Path(__file__).resolve().parents[2] / "scripts" / "sync_docs_site.py"
    return runpy.run_path(str(module_path))


def test_extract_section_stops_at_next_h2() -> None:
    module = _load_sync_module()
    extract_section = module["extract_section"]

    markdown = """# Example\n\n## Alpha\nOne\n\n### Alpha child\nTwo\n\n## Beta\nThree\n"""

    extracted = extract_section(markdown, "Alpha")

    assert extracted == "## Alpha\nOne\n\n### Alpha child\nTwo\n"


def test_extract_section_missing_heading_raises_value_error() -> None:
    module = _load_sync_module()
    extract_section = module["extract_section"]

    with pytest.raises(ValueError, match="Heading not found"):
        extract_section("# Example\n\n## Present\n", "Missing")


def test_build_generated_content_includes_header_and_normalizes_links(tmp_path: Path) -> None:
    module = _load_sync_module()
    build_generated_content = module["build_generated_content"]
    SyncTarget = module["SyncTarget"]

    source = tmp_path / "SECURITY_GUARDRAILS.md"
    source.write_text(
        "# Security\n\n## Security Principles\nRead [SECURITY.md](SECURITY.md).\n",
        encoding="utf-8",
    )

    target = SyncTarget(
        source=source,
        output=tmp_path / "security-principles.mdx",
        sections=("Security Principles",),
    )

    generated = build_generated_content(target)

    assert generated.startswith("{/* This file is generated by scripts/sync_docs_site.py.")
    assert (
        "Read [SECURITY.md](https://github.com/akeesari/remediai/blob/main/SECURITY.md)."
        in generated
    )
